stages:
  - test
  - publish
  - release

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches
    - .kotlin

test-linux:
  stage: test
  before_script:
    - export JAVA_HOME=/home/sdks/zulu-17
  script:
    - ./gradlew
      clean
      linuxX64Test
      --no-daemon
      --stacktrace
  only:
    - master
  tags:
    - linux

test-macos:
  stage: test
  before_script:
    - export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home
  script:
    - ./gradlew
      clean
      macosArm64Test
      --no-daemon
      --stacktrace
  only:
    - master
  tags:
    - macos

test-windows:
  stage: test
  script:
    - ./gradlew
      clean
      mingwX64Test
      --no-daemon
      --stacktrace
  only:
    - master
  tags:
    - windows

publish-linux:
  stage: publish
  before_script:
    - export JAVA_HOME=/home/sdks/zulu-17
  script:
    - ./gradlew
      -DpublishDocs.root=/var/www/docs/multiplatform-dlfcn
      clean
      publishLinux{X64,Arm64}PublicationToGitlabRepository
      publishDocs
      --no-daemon
      --stacktrace
  only:
    - master
  tags:
    - linux

publish-windows:
  stage: publish
  script:
    - ./gradlew
      clean
      publishMingwX64PublicationToGitlabRepository
      --no-daemon
      --stacktrace
  only:
    - master
  tags:
    - windows

publish-macos:
  stage: publish
  before_script:
    - export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home
  script:
    - ./gradlew
      clean
      publishMacos{X64,Arm64}PublicationToGitlabRepository
      --no-daemon
      --stacktrace
  only:
    - master
  tags:
    - macos

create-release:
  stage: release
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  before_script:
    - echo "Fetching project version from libs.versions.toml"
    - export PROJECT_VERSION=$(./gradlew generateVersionInfo --quiet)
  script:
    - echo "Creating release for version $PROJECT_VERSION.$CI_PIPELINE_IID"
  release:
    tag_name: '$(cat .version).$CI_PIPELINE_IID'
    description: '$(cat .version).$CI_PIPELINE_IID'
    ref: '$CI_COMMIT_SHA'
  tags:
    - linux